build: Update production build workflow

diff --git a/.github/workflows/production-build.yml b/.github/workflows/production-build.yml
--- a/.github/workflows/production-build.yml
+++ b/.github/workflows/production-build.yml
@@ -33,9 +33,8 @@ jobs:
         BUILD_REF_NAME: ${{ steps.set_build_ref.outputs.build_ref }}
         REPO_URL: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
       run: |
-        echo "Repo URL: ${REPO_URL}"
-        if ! git ls-remote --tags ${REPO_URL} | grep -q "refs/tags/${BUILD_REF_NAME}$"; then
-          echo "[ERROR] Tag '${BUILD_REF_NAME}' does not exist to build."
+        if ! git ls-remote --tags $REPO_URL | grep -q "refs/tags/$BUILD_REF_NAME$"; then
+          echo "[ERROR] Tag '$BUILD_REF_NAME' does not exist to build."
           exit 1
         fi
 
@@ -52,7 +51,7 @@ jobs:
       run: echo "repo_name=product-dev-release-repo" >> $GITHUB_OUTPUT
 
     - name: Validate git reference for release type
-      uses: ./.github/actions/validate-build-ref@main
+      uses: ravikansangara/base-project/.github/actions/validate-build-ref@main
       with:
         release: ${{ steps.set_release_type.outputs.release_type }}
         branch_tag: ${{ steps.set_git_ref.outputs.git_ref }}
